"""fixed

Revision ID: 0d42979d1ae8
Revises: 7e59a7eeb76f
Create Date: 2026-02-11 13:08:29.949592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d42979d1ae8'
down_revision = '7e59a7eeb76f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_campaign_schedule_unique_slot', 'campaign_schedules', ['campaign_id', 'day_of_week', 'start_time', 'end_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_campaign_schedule_unique_slot', 'campaign_schedules', type_='unique')
    # ### end Alembic commands ###