"""fixed Null

Revision ID: 7e59a7eeb76f
Revises: b37ce2bc7eda
Create Date: 2026-02-11 12:58:17.885371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e59a7eeb76f'
down_revision = 'b37ce2bc7eda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'target_status',
               existing_type=postgresql.ENUM('ACTIVE', 'PAUSED', name='campaignstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'target_status',
               existing_type=postgresql.ENUM('ACTIVE', 'PAUSED', name='campaignstatus'),
               nullable=True)
    # ### end Alembic commands ###