"""initial

Revision ID: b37ce2bc7eda
Revises: 
Create Date: 2026-02-11 11:10:56.551494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37ce2bc7eda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_status', sa.Enum('ACTIVE', 'PAUSED', name='campaignstatus'), nullable=False),
    sa.Column('target_status', sa.Enum('ACTIVE', 'PAUSED', name='campaignstatus'), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('budget_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spend_today', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_days_left', sa.Integer(), nullable=True),
    sa.Column('stock_days_min', sa.Integer(), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_evaluation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('triggered_rule', sa.Enum('DISABLED_MANAGEMENT', 'SCHEDULE', 'LOW_STOCK', 'BUDGET_EXCEEDED', 'NO_RESTRICTIONS', name='triggeredrule'), nullable=True),
    sa.Column('previous_target', sa.Enum('ACTIVE', 'PAUSED', name='campaignstatus'), nullable=True),
    sa.Column('new_target', sa.Enum('ACTIVE', 'PAUSED', name='campaignstatus'), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_evaluation_logs')
    op.drop_table('campaign_schedules')
    op.drop_table('campaigns')
    # ### end Alembic commands ###